apiVersion: v1
kind: Service
metadata:
  name: docker-demo-service
spec:
  selector:
    app: docker-demo
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30003
  type: LoadBalancer
  
  